//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH8P1_knudson
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creature_Equipment
    {
        public int CreatureInstanceID { get; set; }
        public int Head_ItemID { get; set; }
        public int Chest_ItemID { get; set; }
        public int Legs_ItemID { get; set; }
        public int MainHand_ItemID { get; set; }
        public int Seed { get; set; }
        public int CreatureTemplateID { get; set; }
    
        public virtual Item_Armor Item_Armor { get; set; }
        public virtual Item_Armor Item_Armor1 { get; set; }
        public virtual Item_Armor Item_Armor2 { get; set; }
        public virtual Item_Weapon Item_Weapon { get; set; }
        public virtual Creatures Creatures { get; set; }
    }
}
