//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH8P1_knudson
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creature_Inventory
    {
        public int CreatureInstanceID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public int Seed { get; set; }
        public int CreatureTemplateID { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Worlds Worlds { get; set; }
        public virtual Creatures Creatures { get; set; }
    }
}
