//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH8P1_knudson
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.Creature_Inventory = new HashSet<Creature_Inventory>();
        }
    
        public int ItemID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Item_Armor Item_Armor { get; set; }
        public virtual Item_Weapon Item_Weapon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creature_Inventory> Creature_Inventory { get; set; }
    }
}
