//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH8P1_knudson
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Weapon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Weapon()
        {
            this.Creature_Equipment = new HashSet<Creature_Equipment>();
        }
    
        public int ItemID { get; set; }
        public double AttackModifer { get; set; }
        public double ParryModifer { get; set; }
    
        public virtual Items Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creature_Equipment> Creature_Equipment { get; set; }
    }
}
