//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creatures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creatures()
        {
            this.Creature_Inventory = new HashSet<Creature_Inventory>();
        }
    
        public int Seed { get; set; }
        public int CreatureTemplateID { get; set; }
        public int CreatureInstanceID { get; set; }
        public string Name { get; set; }
        public bool IsAlive { get; set; }
        public int Score { get; set; }
        public int RoomID { get; set; }
    
        public virtual Creature_Equipment Creature_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Creature_Inventory> Creature_Inventory { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual CreatureTemplates CreatureTemplates { get; set; }
        public virtual Worlds Worlds { get; set; }
    }
}
