//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Armor
    {
        public int ItemID { get; set; }
        public double EvasionModifer { get; set; }
        public double BlockModifer { get; set; }
        public string EquipmentSlot { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual EquipmentSlot EquipmentSlot1 { get; set; }
    }
}
