//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engine.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureDatabaseEntities : DbContext
    {
        public AdventureDatabaseEntities()
            : base("name=AdventureDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Creature_Equipment> Creature_Equipment { get; set; }
        public virtual DbSet<Creature_Inventory> Creature_Inventory { get; set; }
        public virtual DbSet<Creatures> Creatures { get; set; }
        public virtual DbSet<CreatureTemplates> CreatureTemplates { get; set; }
        public virtual DbSet<EquipmentSlot> EquipmentSlot { get; set; }
        public virtual DbSet<Item_Armor> Item_Armor { get; set; }
        public virtual DbSet<Item_Weapon> Item_Weapon { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Worlds> Worlds { get; set; }
    }
}
